Use chdir in 0.14 terraform
ovotech/circleci-orbs pull request #221
Opened 2021-01-29 09:51 UTC by enicholson125

Terraform 0.14 introduces the -chdir parameter to run terraform in a specific directory. The previous mechanism of specifying the terraform config directory path at the end of the terraform command is deprecated but still works with 0.14 however it does not pick up the provider lock file in the config directory. Instead the provider lock file in the directory the command is being run from is used.

I've attempted to add the chdir command to the orb in a way that supports the pre-0.14 behaviour, so that pre-0.14 terraform should specify the config directory at the end as before while 0.14+ terraform should only specify the chdir parameter.

2021-01-29 09:55 UTC, chris-brindley commented on terraform/apply.sh
> +terraform $chdir plan -input=false -no-color -detailed-exitcode -lock-timeout=300s -out=plan.out $PLAN_ARGS "$config_path" \
Missing quotation marks around `$chdir` here

2021-01-29 11:13 UTC, chris-brindley commented
The only other comment I have is whether we need to include the `--chdir` flag on the `output.sh` command as well. But I don't know enough about the orb to say one way or the other

2021-01-29 13:15 UTC, enicholson125 commented
> The only other comment I have is whether we need to include the `--chdir` flag on the `output.sh` command as well. But I don't know enough about the orb to say one way or the other

Good point, thank you - I think that will need chdir but I'll just run a few experiments locally as I can't see how it's working at present.

2021-02-01 11:49 UTC, enicholson125 commented
> > The only other comment I have is whether we need to include the `--chdir` flag on the `output.sh` command as well. But I don't know enough about the orb to say one way or the other
> 
> Good point, thank you - I think that will need chdir but I'll just run a few experiments locally as I can't see how it's working at present.

The `terraform output` command currently only works if you run it within the directory containing the terraform output config - so it won't currently be working for users who are specifying a different directory in the path parameter. I've added the -chdir parameter so that it will now work as expected for users who specify a path parameter and are using a terraform version >= 0.14, but the existing behaviour won't change for terraform < 0.14 (as `terraform output` doesn't support terminal config directory parameters)

2021-02-01 19:43 UTC, eversC approved these changes

2021-02-01 19:52 UTC, eversC commented
Please could we also update `terraform/CHANGELOG.md` and `terraform/orb_version.txt` accordingly?

2021-02-01 19:53 UTC, eversC requested changes
Please could we also update terraform/CHANGELOG.md and terraform/orb_version.txt accordingly?

2021-02-08 20:28 UTC, eversC requested changes

2021-02-08 20:28 UTC, eversC commented on terraform/validate.sh
> +terraform "$chdir" init -input=false -backend=false -no-color "$config_path"
it seems as though this is coming out as:

```bash
terraform -chdir=cluster init -input=false -backend=false -no-color ''
```

and the single quotes at the end are breaking it.

2021-02-16 16:04 UTC, eversC approved these changes

2021-02-16 16:05 UTC, eversC commented
seems like your dev testing was successful @enicholson125 , as was the brief spell I just conducted

lgtm 🎆

2021-02-16 16:09 UTC, merged